### This is the Terraform-generated prod-promote.yml workflow for the archival-packaging-tool-prod repository. ###
### If this is a Lambda repo, uncomment the FUNCTION line at the end of the document.         ###
name: Prod Container Promote

# checkov:skip=CKV2_GHA_1:The shared workflow contains the permissions constraints
# NOTE: The above checkov skip command doesn't actually work and this workflow
#       will always show a checkov warning.

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Prod Container Promote
    uses: mitlibraries/.github/.github/workflows/ecr-shared-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: archival-packaging-tool-gha-stage
      GHA_ROLE_PROD: archival-packaging-tool-gha-prod
      ECR_STAGE: "archival-packaging-tool-stage"
      ECR_PROD: "archival-packaging-tool-prod"
      FUNCTION: "archival-packaging-tool-prod"
 